from fractions import gcd
from functools import reduce

# Project Euler 1-10

print 'Project Euler: #1 - 10'

# Problem 1
# If we list all the natural numbers below 10 that are multiples of 3 or 5,
# we get 3, 5, 6 and 9. The sum of the multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.
def one(x):
    sum = 0
    for num in range(0,x):
        if num % 3 == 0 or num % 5 == 0:
            sum += num
    return sum

print 'Problem 1:', one(1000)

# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms.
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def two(lim):
    first, next = 0, 1
    sum = 0
    while first < lim:
        if not first % 2:
            sum += first
        first, next = next, first + next
    return sum

print 'Problem 2:', two(4000000)

# Problem 3
# The prime factors of 13195 are 5, 7, 13, and 29.
# What is the largest prime factor of the number 600851475143?

def three(num):
    fac = 2
    while fac < num:
        while num % fac == 0:
            num = num / fac
        fac += 1
    return fac

print 'Problem 3:', three(600851475143)

# Problem 4
# A palindromic number reads the same both ways. The largest
# palindrome made from the product of two 2 digit numbers is 9009 = 91 x 99.
# Find the largest palindrome made from the product of two 3 digit numbers.

def four(min, max):
    palindrome = 0
    for x in range(min, max + 1):
        for y in range(x + 1, max + 1):
            xy = x * y
            if xy > palindrome and (str(xy) == str(xy)[::-1]):
                palindrome = xy
    return palindrome

print 'Problem 4:', four(100,999)

# Problem 5
# 2520 is the smallest number than can be divided by each of the numbers
# from 1 to 10 wthout any remainder.
# What is the smallest positive number that is evenly divisble by all of the
# numbers from 1 to 20?

def five(max):
    num = max
    div = False
    while not div:
        for x in range(1, max+1):
            if num % x != 0:
                num += 1
                break
            if x == max:
                div = True
    return num

print 'Problem 5:', five(20)
